Real-Estate
codedamn/projects pull request #185
Opened 2022-10-18 03:53 UTC by shubhra-g

2022-10-18 11:55 UTC, Pranavtechie requested changes
Upload the icon directly to the boilerplate repo instead of an min.css file 

font.txt contains css reset code, which should have been clearly part of the steps mentioned 

Please download the .ttf format files of the font instead of google fonts 

I see that all the images are not in the same format, it is best to keep all the images in webp, jpg or png. Convert them to a single format as per your wish. (This is to avoid any kind of confusion while importing files) 

UPload a screenshot of the mobile design of the page as well, making responsiveness part of the project 


**Please go through all the mentioned changes in the reivew, if you feel that you have a doubt, feel free to ping me directly in this discussion. **

2022-10-18 11:55 UTC, Pranavtechie commented on Real_Estate/spec.yml
> +name: Real-Estate
Please update the name of the project to `Real Estate website landing page`

2022-10-18 11:55 UTC, Pranavtechie commented on Real_Estate/spec.yml
> +long-description: |
The long description should contain the details regarding the landing page that the user is gong to developer, Please re-write the entire long description

2022-10-18 11:55 UTC, Pranavtechie commented on Real_Estate/step0/instructions.md
> +- Create a class ```navbar-container``` which includes  ```logo``` of "R-state" , a ```menu-icon``` , a unordered list class displaying  home , about , sales and properties.In the end create a ```log
Please be thorough when writing instructions and always provide context to what you are referring to

2022-10-18 11:55 UTC, Pranavtechie commented on Real_Estate/step0/instructions.md
> +- Create a class ```navbar-container``` which includes  ```logo``` of "R-state" , a ```menu-icon``` , a unordered list class displaying  home , about , sales and properties.In the end create a ```log
For example you can point out the logo's path etc. 

You should make use of single backtick when writing an inline codeblock. 

When writing a codeblock you have to make use of triple backticks. Please update this as well

2022-10-18 11:55 UTC, Pranavtechie commented on Real_Estate/step0/challenges.yml
> +    -text: "add the logo"
Rephrase the challenges to give a clear cut understand, the challenges should be concise in nature, but you can make it up to 5 - 15 words, not 3-5 words.

2022-10-18 11:55 UTC, Pranavtechie commented on Real_Estate/step0/challenges.yml
> +    -text: "add the logo"
Rephrase the challenges to give a clear cut understand, the challenges should be concise in nature, but you can make it up to 5 - 15 words, not 3-5 words.

2022-10-18 11:55 UTC, Pranavtechie commented on Real_Estate/step1/challenges.yml
> +name: "creating the section for home and adding a image and sign-up button"
Please keep the step names as short as possible, they'll be displayed in the sidebar

2022-10-19 05:18 UTC, shubhra-g commented
how to upload the icon to the boilerplate repo

2022-10-21 08:04 UTC, shubhra-g commented
???

2022-11-07 05:05 UTC, closed without merging