Dice game project re-added after fixes
codedamn/projects pull request #236
Opened 2022-11-12 07:52 UTC by BarmenduC

The 2 notified issues regarding the spec.yaml has been fixed. Do mention if something else needs to be changed.

2022-11-15 14:57 UTC, BarmenduC commented
@Pranavtechie @mehulmpt 
I was instructed to add the file after fixes before the 13th of November, which I did.
Is my submission still valid for the hacktoberfest challenge?

2022-11-15 17:03 UTC, Pranavtechie commented
@BarmenduC Please remove the .DS_Store file from the boilerplate repo, You might not able to find this fine in you local-system if you did not enable to show hidden files. 

If you're still unable to see this file, you can attempt to delete this file directly from the command line from the github repo directly itself

2022-11-15 17:04 UTC, Pranavtechie commented
@BarmenduC Also there are no `style.css` and `script.js` files in your boilerplate repo, then remove those names form the `files` in the `.cdmrc` file

2022-11-15 17:24 UTC, Pranavtechie requested changes

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/spec.yml
> +    - Download the starter code and go through the README.md file.
Remove this line, as user's don't have to download

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/spec.yml
> +    The `README.md` file will provide further details about the project. The `style-guide.html` file is where you'll find colors, fonts, etc.
Please remove this line as well, there is no `style-guide.html`  or `Readme.md` in your boilerplate repo

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step0/Instructions.md
> +Hello there, welcome to the first step of Dice game project in which we intend to develop a 2 player dice game having 2 seperate dice on the screen for both the player, which on the press of a button
for both the players 

`s` is missing here

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step1/Instructions.md
> +1. Add a new `<div> </div>` tag inside the `<body>` element. Give the `<div>` element an id `gallery-container`, this element will act as a container and will have all the gallery images inside this
@BarmenduC You've clearly copied this content from the mutliverse gallery project. Please re-write this or we'll reject your project.

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step2/Instructions.md
> +<html>
Add code block for this using triple backticks (`)

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step2/challenges.yml
> +  - text: "Link the JS file to HTML (If you wish to know how, check instruction number 3)"
Remove the text in brackets, the instruction number as not visible to users, only the step names are visible

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step3/Instructions.md
> +   for example:
make sure that the code blocks contain proper comments, do not add any normal lines inside the codeblocks

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step3/Instructions.md
> +   for example:
Do not add `a)` in the codeblocks directly, they affect the overall way the codeblock is represented. You can add this text in the codeblock by commenting them in the css file using ` /* */`

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step3/Instructions.md
> +If you have reached till here, let's move on to the next step.
Try rephrasing this line to `You're halfway through the project, great job!` or remove the line altogether

2022-11-15 17:24 UTC, Pranavtechie commented on dice-game-project/step4/Instructions.md
> +```json
This is not JSON codeblock, this is `javascript` please use `js` instead of `json`

2022-11-15 18:52 UTC, BarmenduC commented
@Pranavtechie 
All mentioned changes have been made.

2022-11-17 01:16 UTC, BarmenduC commented
@Pranavtechie Is it acceptable now?

2022-11-18 08:27 UTC, BarmenduC commented
@Pranavtechie @mehulmpt All previously requested changes have been made. Do provide a final confirmation whether the entry is accepted or not. Thanks in advance

2022-11-18 10:00 UTC, Pranavtechie commented on dice-game-project/step2/challenges.yml
> +  - text: "Link the JS file to HTML. If you wish to know how, check instruction number 3"
**Remove the Instruction Number 3 text and mentioned if the step name**

2022-11-18 10:00 UTC, Pranavtechie commented on dice-game-project/step3/Instructions.md
> +background-color: lightblue;
Add appropriate indentation here

2022-11-18 10:01 UTC, Pranavtechie commented on dice-game-project/step4/Instructions.md
> +Math.random() function in Javascript generates a random number between 0 and 1. Multiplying it by 5 we get a random number between 0 and 5 which might be a decimmal number. When combined with math.fl
Wrap inline code in backticks

2022-11-21 00:23 UTC, BarmenduC commented
@Pranavtechie @mehulmpt 
All mentioned changes have been implemented.
Please perform check for merge

2022-11-22 16:57 UTC, BarmenduC commented
@Pranavtechie @mehulmpt 
Please review changes.

2022-11-24 09:01 UTC, BarmenduC commented
@Pranavtechie @mehulmpt Will this entry not be acceptable anymore?
If yes, please review and merge.

2023-02-08 18:16 UTC, closed without merging