made a guided project on bmi-calculator with steps and challenges
codedamn/projects pull request #39
Opened 2022-10-03 01:47 UTC by pranayjalan254

made a repository where the design and the html boilerplate code is ready. Please review it

2022-10-03 09:51 UTC, Pranavtechie requested changes
@pranayjalan254 Can you update the step folder names. 

The folder names should not consist of `space` 

The `stepId` should match with the folder name. 

So the folder name should be `step1` , `step2` ...

2022-10-03 10:52 UTC, pranayjalan254 commented
yeah sure.

2022-10-03 10:53 UTC, pranayjalan254 commented
if you could help me how to change the folder names, it would be great help.

2022-10-04 03:56 UTC, pranayjalan254 commented
Kindly review it. Please. Will modify it as required

2022-10-04 09:37 UTC, Pranavtechie commented
@pranayjalan254  Your boilerplate github repo does not contain the `.cdmrc` file. Can you add it. You can refer to this [documentation](https://codedamn.com/news/product/how-to-use-codedamn-playgrounds#File_READMEmd). 

Adding the below mentioned lines is enough for now. 

```
terminal-one: static-server -p 1337 --no-cache
tabs: ['index.html']
```

2022-10-04 09:48 UTC, pranayjalan254 commented
done sir, kindly review and merge my pull request.

2022-10-05 05:46 UTC, pranayjalan254 commented
@mehulmpt @Pranavtechie please review this pull request and ask for changes if required..

2022-10-05 10:51 UTC, Pranavtechie commented on bmi-calculator/spec.yml
> +cover-image: https://github.com/pranayjalan254/codedamn-bmi-calculator/blob/main/designs/Final%20design.jpg
Can you update the cover-image so that it uses the direct image link : the link would be

https://raw.githubusercontent.com/pranayjalan254/codedamn-bmi-calculator/main/designs/Final%20design.jpg

for your image.

2022-10-06 02:22 UTC, pranayjalan254 commented
Updated the cover image link. Please review it

2022-10-06 06:17 UTC, Pranavtechie requested changes
Try and improve the instructions given in all steps, the instructions should be as elaborate as possible, such that they help the user in completing the given challenges in each steps. 

You can refer to the already built guided projects, bird-app and multiverse-photo-gallery-project

2022-10-06 06:17 UTC, Pranavtechie commented on bmi-calculator/step0/Instructions.md
> +There are some criteria that will help you determine which class you belong in, such as underweight, healthy, overweight, and obese. You can better understand it by looking at the chart below.
You can also include elaborate instructions here (not necessarily complete code) that help in solving the challenges mentioned in each steps

2022-10-06 06:17 UTC, Pranavtechie commented on bmi-calculator/step1/Instructions.md
> +## Style it as you want
You could also have mentioned the current styles that you have used here

2022-10-06 06:33 UTC, pranayjalan254 commented
okay sir, will do the required changes

2022-10-06 07:00 UTC, pranayjalan254 commented
Done. Kindly review it and all the typos (if there) are fixed. @Pranavtechie

2022-10-06 17:03 UTC, Pranavtechie requested changes

2022-10-06 17:03 UTC, Pranavtechie commented on bmi-calculator/step3/Instructions.md
> +## Use some styles to add the background color and some width and margin to the box. Also add some styles like increasing font size and text-alignment property to the webpage
You could also mention the styles that the user has to use, at least the width and typography

2022-10-06 17:03 UTC, Pranavtechie commented on bmi-calculator/step3/challenges.yml
> +    - text: 'No set height and will be determined by the amount of content'
Can you rephrase these two challenges, I couldn't understand them correctly. Let me know what you were trying to convey

2022-10-06 17:03 UTC, Pranavtechie commented on bmi-calculator/step4/challenges.yml
> +    - text: 'add the formula for calculating the BMi. First and foremost, we will accept the user’s weight and height, and then we will add that value to the formula. Whatever the value is, we will c
Here, I can see the role reversal of challenges and instructions page. The step4 breakdown can be re-written. The challenges need to concise & to the point, whereas the instructions should give an elaborate explanation of what needs to be done with some details.

2022-10-07 01:31 UTC, pranayjalan254 commented on bmi-calculator/step2/challenges.yml
> +    - text: 'Now using the input with type as “button” add the onlick function to our button for the javascript button . Also use some style to add the background color and with some width and margin
i did not get you, please elaborate

2022-10-07 01:36 UTC, pranayjalan254 commented
Please review. @Pranavtechie

2022-10-08 03:06 UTC, pranayjalan254 commented
Please tell if any other things to be modified... Thank You

2022-10-09 04:33 UTC, pranayjalan254 commented
@Pranavtechie

2022-10-09 13:10 UTC, pranayjalan254 commented
hey @Pranavtechie did received any further reviews for my project...Is the PR completed

2022-10-10 17:04 UTC, pranayjalan254 commented
No further comments?? @Pranavtechie @mehulmpt

2022-10-10 17:57 UTC, mehulmpt commented
Hi Pranay
Continuously pinging us to review would not help. If anything, it just annoys me and everyone who subscribed to this issue. We are not ignoring our PR, we will review it. Please be patient.

2022-10-10 17:59 UTC, mehulmpt requested changes
Need many changes

2022-10-10 17:59 UTC, mehulmpt commented on bmi-calculator/spec.yml
> +  Your challenge is to build out this bmi calculator and get it looking as close to the design as possible.
Your `long-description` field is completely wrong (and copied from other projects). Please refactor this to include proper changes.

2022-10-10 17:59 UTC, mehulmpt commented on bmi-calculator/step1/Instructions.md
> +background-color: #f6f6f6
What is this exactly? Code or content copy? If code, please use backticks and syntax highlighting

2022-10-10 17:59 UTC, mehulmpt commented on bmi-calculator/step1/Instructions.md
> +## In this step you need to add the heading and slider using HTML.
Why do you have two headings continuously?

2022-10-10 17:59 UTC, mehulmpt commented on bmi-calculator/step2/Instructions.md
> +## Make sure you style it properly
Wrong use of markdown headings

2022-10-10 17:59 UTC, mehulmpt commented on bmi-calculator/step4/Instructions.md
> +## First and foremost, we will accept the user’s weight and height, and then we will add that value to the formula. Whatever the value is, we will compare it using the for loop, and then define the p
Wrong use of markdown headings

2022-10-10 17:59 UTC, mehulmpt commented on bmi-calculator/step4/Instructions.md
> +## First and foremost, we will accept the user’s weight and height, and then we will add that value to the formula. Whatever the value is, we will compare it using the for loop, and then define the p
Please learn about markdown: https://www.markdownguide.org/basic-syntax/

2022-10-11 04:03 UTC, pranayjalan254 commented
> Hi Pranay Continuously pinging us to review would not help. If anything, it just annoys me and everyone who subscribed to this issue. We are not ignoring our PR, we will review it. Please be patient.

I am extremely sorry sir, will do the required changes. Will not ping you again. Sorry

2022-10-16 11:04 UTC, Pranavtechie requested changes
Hey @pranayjalan254 , please go through the written text before submitting, there are lot of simple mistakes that could have been avoided. 

Before starting to edit this project, I'd recommend you to get the complete idea of how our guided project work. Please go through an existing guide projects code and try and open it as a guided project on the website to understand it's working. 

This will give you a good idea on how to write the project.

2022-10-23 05:39 UTC, Pranavtechie commented
@pranayjalan254 are you working on the requested changes, just wanted to get an update.

2022-10-25 12:47 UTC, pranayjalan254 commented
sorry, was busy settling in the admitted college, will try to resume the work soon

2022-10-31 09:45 UTC, Pranavtechie commented
@pranayjalan254 Please make the requested changes as soon as possible

2022-11-11 05:57 UTC, Pranavtechie commented
@pranayjalan254 The challenges and the Instructions are not up to the mark and would require a complete re-write from your end. I'm closing this PR, feel free to open a new PR when you have rewritten the challenges. 

Please refer to existing projects to understand how to write the challenges and Instructions. 

As this is a beginner project the instructions need to be very clear and explain why you are taking the particular step. You can refer to https://codedamn.com/project/multiverse-html5-photo-gallery/

2022-11-11 05:57 UTC, closed without merging