Flipkart clone added
codedamn/projects pull request #44
Opened 2022-10-03 18:44 UTC by harshilsharmaa

Flipkart clone project with all steps and challenges added.

2022-10-05 10:47 UTC, Pranavtechie requested changes
Your Boilerplate repo does not contain `.cdmrc` configuration file. 

Please refer to [https://teach.codedamn.com/docs/concepts/cdmrc](https://teach.codedamn.com/docs/concepts/cdmrc) add the file in your starter files repo

2022-10-05 16:43 UTC, harshilsharmaa commented
Updated and .cdmrc configuration file added.

2022-10-06 06:46 UTC, Pranavtechie requested changes
Hey @harshilsharmaa, you've done a great job in breaking down the project into simple steps. 

You can work on making the Instructions more specific and elaborate such that they help the user in completing the challenges.

2022-10-06 06:46 UTC, Pranavtechie commented on flipkart-clone/step3/challenges.yml
> +    - text: 'Tesr your APIs using postman or any other API testing tool'
Typo at `Tesr`

2022-10-06 17:20 UTC, harshilsharmaa commented on flipkart-clone/step3/challenges.yml
> +    - text: 'Tesr your APIs using postman or any other API testing tool'
Typo Corrected.

2022-10-06 17:21 UTC, harshilsharmaa commented
Updated Instructions to get better understanding to the users.

2022-10-09 09:10 UTC, harshilsharmaa commented
Please review this.

2022-10-22 09:42 UTC, Pranavtechie requested changes

2022-10-22 09:42 UTC, Pranavtechie commented on flipkart-clone/step1/Instructions.md
> +- Add Products
I couldn't find the details of the product, where they being fetched from

2022-10-22 09:42 UTC, Pranavtechie commented on flipkart-clone/step10/Instructions.md
> +1. use hooks like useState and useEffect etc.
Please provide the context to the user in the Instructions file as well, regarding where to do.

2022-10-22 09:42 UTC, Pranavtechie commented on flipkart-clone/step10/challenges.yml
> +name: 'Show the data on components'
Rename step to "Displaying Data"

2022-10-23 05:41 UTC, Pranavtechie commented
@harshilsharmaa are you working on the requested changes?

2022-10-23 05:58 UTC, harshilsharmaa commented
> @harshilsharmaa are you working on the requested changes?

Yes, Iam working on it.

2022-11-08 06:36 UTC, closed without merging