Added step wise guided `Add visitors to repo's README.md` project.
codedamn/projects pull request #48
Opened 2022-10-04 16:46 UTC by tanishq-singh-2301

2022-10-04 18:20 UTC, mehulmpt commented
Thanks for the PR, someone would review from the team shortly

2022-10-05 07:42 UTC, Pranavtechie requested changes
Hey Tanishq, the structure checks out. Great Job!

Can you improve the instructions written in step0 and step1 to match the challenges given the respective steps. I feel that we can include more instructions so that the user is aware of what he needs to do.  

You can also include the Complete Overview of the project from the README.md in the step0 instructions as well. 

Also as the user is supposed to push these changes to the GitHub repository after working with  code on Codedamn Playgrounds, can you add few instructions on how to login  to a GitHub account in Codedamn Playgrounds. as currently users cannot login using passwords and have to make use of Access Tokens. 

Feel free to message back if you have questions.

2022-10-05 08:17 UTC, tanishq-singh-2301 commented
Working on it!

2022-10-05 10:04 UTC, tanishq-singh-2301 commented
Made all the changes requested.
Kindly review my code @Pranavtechie @mehulmpt

Thanks.

2022-10-05 10:43 UTC, Pranavtechie commented on add-visitors-to-github-readme/step2/challenges.yml
> +  - text: "git add README.md"
I'm referring to the last three challenges in the step2

2022-10-05 11:02 UTC, tanishq-singh-2301 commented
Rephrased the challenges in step2,
Please review it @Pranavtechie 

Thanks.

2022-10-06 06:33 UTC, tanishq-singh-2301 commented
Any update @mehulmpt  @Pranavtechie

2022-10-06 17:07 UTC, Pranavtechie reviewed
@tanishq-singh-2301 Everything looks good. We'll merge this soon!

2022-10-06 17:09 UTC, tanishq-singh-2301 commented
Okay

2022-10-09 12:36 UTC, tanishq-singh-2301 commented
any update? @Pranavtechie  @mehulmpt

2022-10-14 04:56 UTC, tanishq-singh-2301 commented
@mehulmpt can you please review this pr?

2022-10-20 12:59 UTC, tanishq-singh-2301 commented
any update?? @Pranavtechie @mehulmpt

2022-10-31 09:43 UTC, Pranavtechie approved these changes

2022-10-31 09:44 UTC, merged

2022-11-11 05:51 UTC, Pranavtechie commented
@tanishq-singh-2301 Please share your email address here or reach out to me at pranav@codedamn.com

2022-11-11 17:49 UTC, tanishq-singh-2301 commented
It's tanishqsingh640@gmail.com @Pranavtechie