added terminal-page
codedamn/projects pull request #52
Opened 2022-10-05 03:10 UTC by flyingsonu122

build  web pages (website) looking like terminal

2022-10-05 03:13 UTC, flyingsonu122 commented
@mehulmpt pls review and merge this, thanks

2022-10-05 10:57 UTC, Pranavtechie requested changes

2022-10-05 10:57 UTC, Pranavtechie commented on terminal-page/README.md
> +# Terminal Page
Hey Sonu, can you remove the README.md file from this repo, you can add this in the boilerplate/starter-file repo

2022-10-05 13:27 UTC, flyingsonu122 commented
@Pranavtechie deleted , pls review and merge, thanks

2022-10-06 11:46 UTC, flyingsonu122 commented on terminal-page/README.md
> +# Terminal Page
Resolved it, pls review

2022-10-07 12:47 UTC, flyingsonu122 commented
Hi @mehulmpt @Pranavtechie  pls review and merge, regards

2022-10-23 05:47 UTC, Pranavtechie requested changes
Your Project does not mention how to use the `winbox` library and you have to write detailed Instructions for each step, please refer to 

you can go through existing guided project folders to understand how to make a guided project. You can go through `bird-app` and multiverse `multiverse-html5-photo-gallery` projects to understand better.

2022-10-23 05:47 UTC, Pranavtechie commented on terminal-page/spec.yml
> +  Wish you all the best"
Remove the extra double quotes at the end of the line

2022-10-23 05:47 UTC, Pranavtechie commented on terminal-page/step0/Instructions.md
> +include div tag then nav tag then ul tag after that add two li tags
The Instructions page should contain detailed instructions to complete the challenges mentioned in the step. You have only written a single line here.  Please re-write the instructions.

2022-11-11 09:23 UTC, Pranavtechie commented
Closing PR due to inactivity and not resolving the requested changes

2022-11-11 09:23 UTC, closed without merging