Added NFT Marketplace guided project
codedamn/projects pull request #53
Opened 2022-10-05 06:12 UTC by navyansh007

As per the feedback, I converted this project into a guided project, which will guide learners to make an NFT Marketplace- a real-world project that will help them to learn key Web3 and Blockchain concepts. By building this project, they will also get the experience of making something that can be used by actual users.

I, as the developer of this starter code and guided project, hope that this will add value to the learning journey of the budding blockchain developers. I am open to corrections that can be done and would be more than happy if this project gets added to CodeDamn's list of various interesting projects.

2022-10-05 11:05 UTC, Pranavtechie requested changes

2022-10-05 11:05 UTC, Pranavtechie commented on nft-marketplace/step2/challenges.yml
> +stepId: step2
Can you add the challenges for the step2

2022-10-05 11:11 UTC, navyansh007 commented on nft-marketplace/step2/challenges.yml
> +stepId: step2
There is just one step here which is very basic, so the step breakdown is still required?

2022-10-05 11:28 UTC, navyansh007 commented on nft-marketplace/step2/challenges.yml
> +stepId: step2
I have added the possible step breakdown in step 2. Please review the change, and if everything is good, please merge the branch.

2022-10-06 11:00 UTC, navyansh007 commented
Hey @Pranavtechie
Please add hacktoberfest label to the repo so that this contribution gets eligible for Hacktoberfest.

2022-10-10 06:30 UTC, navyansh007 commented
Hello, @Pranavtechie @mehulmpt @rishabhrao
Just a kind reminder, the changes requested by @Pranavtechie and @mehulmpt have been implemented in the code. Please merge the code in the master branch of Codedamn's projects repo if everything is good to go.

2022-11-04 04:53 UTC, merged

2022-11-08 13:56 UTC, navyansh007 commented
Hey @Pranavtechie , 
Since this PR has been accepted, may you please tell me what are the next steps?

2022-11-09 03:47 UTC, Pranavtechie commented
@navyansh007 please share your email address here , or reach out to me at pranav@codedamn.com

2022-11-09 09:13 UTC, navyansh007 commented
Here is my email id: navyanshkesarwani@gmail.com