Meme Generator
codedamn/projects pull request #56
Opened 2022-10-05 08:01 UTC by Sambhav250703

Mini project on Meme Generator using HTML, CSS & Javascript for Hacktoberfest 2022.

2022-10-05 11:07 UTC, Pranavtechie commented
Hey @Sambhav250703, can you convert your project into a guided project. 

Also can you rename the file from `spec.yaml` to `spec.yml` for consistency

2022-10-05 11:08 UTC, Pranavtechie requested changes
- converting the project into a guided project 
- updating the file name to `spec.yml`

2022-10-05 11:15 UTC, Sambhav250703 commented
Guided project means I must explain all the steps right how I developed this project and which api I had used ?

2022-10-07 01:36 UTC, Sambhav250703 commented
Please give a update and label my pr for hacktoberfest.

2022-10-07 17:37 UTC, Sambhav250703 commented
https://github.com/codedamn/projects/issues/40

2022-10-08 10:13 UTC, Sambhav250703 commented
Can you check and merge the pr so it will count for my hacktoberfest 2022

2022-10-31 10:01 UTC, Pranavtechie submitted a review, later dismissed

2022-10-31 10:01 UTC, Pranavtechie commented on Meme Generator/spec.yml
> +host-files: https://sambhav250703.github.io/Hacktoberfest-codedamn/
remove host-files

2022-10-31 10:08 UTC, Sambhav250703 commented on Meme Generator/spec.yml
> +host-files: https://sambhav250703.github.io/Hacktoberfest-codedamn/
Done changes pls check it out and merge the pr

2022-11-01 11:52 UTC, Sambhav250703 commented
Any more changes I want to do for get accepted and merging the pr @Pranavtechie

2022-11-05 04:05 UTC, Pranavtechie approved these changes

2022-11-05 04:22 UTC, merged