collaborative code editor guided project added
codedamn/projects pull request #60
Opened 2022-10-05 11:53 UTC by oneknucklehead

Added the steps guiding the user through the project.

2022-10-06 03:23 UTC, Pranavtechie requested changes
I've also made 2 PRs in the Starter file repo. Please merge them. 

Also you can move the package.json file into the server folder, so that the client and server files are isolated completely. (Once done, please update the .cdmrc accordingly as well) 

You can also reduce the boilerplate code in the server.js file and instruct those changes in the project instructions. 

You can also elaborate a little hard parts of the instructions by guiding users with small code snippets.

2022-10-06 03:23 UTC, Pranavtechie commented on collaborative-code-editor/spec.yml
> +type: frontend
You can convert this to fullstack as your also building the server.

2022-10-09 08:22 UTC, oneknucklehead reviewed
Made the said changes

2022-11-02 19:00 UTC, oneknucklehead commented
Hey! @Pranavtechie just following up on the PR, i had made the said changes. If things are all okay, we can gtm

2022-11-04 19:42 UTC, merged

2022-11-11 06:04 UTC, Pranavtechie commented
@oneknucklehead Please share your email address here or reach out to me at [pranav@codedamn.com](mailto:pranav@codedamn.com)

2022-11-11 08:52 UTC, oneknucklehead commented
> @oneknucklehead Please share your email address here or reach out to me at [pranav@codedamn.com](mailto:pranav@codedamn.com)

Here's my email: zohebcool1542@gmail.com