Facebook-project-added
codedamn/projects pull request #65
Opened 2022-10-05 13:00 UTC by Lakshay-Pruthi

I have added Facebook Sign-up page clone guided project.

2022-10-06 04:53 UTC, Pranavtechie requested changes
You Need to rename all the instructionsmd file to `Instructions.md` (Capital Letter I) 

As mentioned earlier, you might also have to do a dummy commit here to change the character case of the file.

2022-10-06 04:53 UTC, Pranavtechie commented on facebook-SignUp-page-clone/spec.yml
> +cover-image: https://github.com/Lakshay-Pruthi/facebook-clone-html-playground-starter/blob/master/Project-Design/Screenshot%202022-10-05%20175946.png
Need to add the direct image link : raw.githubusercontent. ...

2022-10-06 04:53 UTC, Pranavtechie commented on facebook-SignUp-page-clone/spec.yml
> +name: Facebook Sign-up page project
Can you change the folder name to only include lowercase letters. 

You may have to do a dummy commit, as git doesn't register changes if the case of the characters is changed. 
So make changes to the folder name commit changes and then make a change again (make sure that all the characters are lowercase now) and then commit again

2022-10-06 04:53 UTC, Pranavtechie commented on facebook-SignUp-page-clone/step0/instructions.md
> +"https://static.xx.fbcdn.net/rsrc.php/y8/r/dF5SId3UHWd.svg"
Can you download this image and create an `/assets` folder in the boilerplate repo and add it there, it is recommended to have all static assets locally in the playground itself.

2022-10-06 10:53 UTC, Lakshay-Pruthi commented
@Pranavtechie , I have made all the changes. Please review it.

2022-11-08 10:21 UTC, Pranavtechie commented
Merging these commits from here https://github.com/codedamn/projects/pull/225

2022-11-08 10:21 UTC, closed without merging

2022-11-10 04:50 UTC, Lakshay-Pruthi commented
@Pranavtechie 👍🏻