added astral-portfolio-page!
codedamn/projects pull request #66
Opened 2022-10-05 13:38 UTC by Tamanna-S

hello, i have made this a guided project by adding spec.yml and 6 steps that contains challenges.yml and instructions.md.
check this out and let me know if that's okay.

Working on Astral Portfolio Project #33

2022-10-05 17:25 UTC, Pranavtechie requested changes

2022-10-05 17:25 UTC, Pranavtechie commented on astral-portfolio-page/step0/Instructions.md
> +so, here goes the instructions for step0 :
@Tamanna-S , you can remove the `step0` text from the instructions page. We do not share this numbers with the users anywhere

2022-10-05 17:25 UTC, Pranavtechie commented on astral-portfolio-page/step1/instructions.md
> +Welcome in the next step!
The Name of the file `instructions` is in lowercase, can you change it to `Instructions.md`

2022-10-05 17:25 UTC, Pranavtechie commented on astral-portfolio-page/step1/instructions.md
> +Welcome in the next step!
Grammer : `In this step, you'll be building, doing .... `

2022-10-05 17:25 UTC, Pranavtechie commented on astral-portfolio-page/step2/instructions.md
> +huh! champ welcome in the styling part.
renaming to capital I `Instructions.md`

2022-10-05 17:25 UTC, Pranavtechie commented on astral-portfolio-page/step3/instructions.md
> +welcome in the part of styling the contact page!
Capital I in the file name

2022-10-05 17:25 UTC, Pranavtechie commented on astral-portfolio-page/step6/instructions.md
> +finally the last step and you have completed a nice portfolio project!!!
@Tamanna-S, the first Instructions.md contains the capital letter you need to rename the rest of the files. 

Remember that changing a single letter doesn't get recognized on git. For that you have to rename the file name with an extra charact and then commit the changes made, and then go back and update the file name to `Instructions.md`

2022-10-06 03:45 UTC, Tamanna-S commented
really sorry for the mistakes fixing them all!!

2022-10-06 04:32 UTC, Tamanna-S commented
hey please i messed up with the branch may i open a new pr and close this?

2022-10-06 04:33 UTC, closed without merging