made astral-portfolio-page a guided project
codedamn/projects pull request #72
Opened 2022-10-06 04:43 UTC by Tamanna-S

really really sorry, i messed up, so i closed the last pr.
this is my new pr with the same issue, kindly check this and let me know if now its okay.
Working on Astral Portfolio Project #33

2022-10-06 05:31 UTC, Pranavtechie requested changes
Instructions and challenges are pretty much the same, you can write more detailed instructions in the instructions, you can refer from `https://codedamn.com/project/multiverse-html5-photo-gallery`, this has actually given a lot of snippets. 

You don't need to give all the required steps, but a lot of snippets will be better

2022-10-06 05:31 UTC, Pranavtechie commented on astral-portfolio-page/step1/Instructions.md
> +    - paste this cdn in your index.html <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
You can mention the icon names here as well.

2022-10-06 05:31 UTC, Pranavtechie commented on astral-portfolio-page/step1/challenges.yml
> +name: 'Writing html files in all pages!'
Avoid using `!` exclamation mark at the end of step names and heading, these as the step names will be displayed together in the steps side-bar

2022-10-06 05:34 UTC, Tamanna-S commented
alright @Pranavtechie and thank you vary much.

2022-10-10 14:21 UTC, Tamanna-S commented on astral-portfolio-page/step1/Instructions.md
> +    - paste this cdn in your index.html <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
done

2022-10-10 14:22 UTC, Tamanna-S commented
hey @Pranavtechie  sorry for the delay, may you please check now and lemme know if that's okay.

2022-10-13 05:57 UTC, Tamanna-S commented
> hey @Pranavtechie sorry for the delay, may you please check now and lemme know if that's okay.

.

2022-11-08 03:34 UTC, Pranavtechie approved these changes

2022-11-08 03:34 UTC, merged

2022-11-11 06:17 UTC, Pranavtechie commented
@tamannasgh Please share your email address here or reach out to me at [pranav@codedamn.com](mailto:pranav@codedamn.com)

2022-11-11 06:45 UTC, tamannasgh commented
hey @Pranavtechie here it is:
ts.harma2882006@gmail.com