keep-html5-note-taking-app
codedamn/projects pull request #73
Opened 2022-10-06 08:07 UTC by CHAMP010

hactoberfest2022 submission.

2022-10-13 17:58 UTC, Pranavtechie requested changes
Hey @CHAMP010 , the `.cdmrc` and the `index.html` file should be in the boilerplate repo. 

Please refer tot he documentation, and already existing guided project for better understanding.

2022-10-17 14:19 UTC, CHAMP010 commented
Please review it.

2022-11-05 04:48 UTC, Pranavtechie requested changes
Hey @CHAMP010 , you've done a good job at writing down the Instructions. Please make the mentioned changes to get your PR ready. 

Please also drop your email address here or you can email to pranav@codedamn.com

2022-11-05 04:48 UTC, Pranavtechie commented on keep-html5-note-taking-app/spec.yml
> +cover-image: https://raw.githubusercontent.com/codedamn-projects/keep-html5-note-taking-app/master/designs/Note%20Taking%20%5BDesktop%5D.jpg
The cover image gives a 404, please add this image to the boilerplate repo and update the link here

2022-11-05 04:48 UTC, Pranavtechie commented on keep-html5-note-taking-app/step2/Instructions.md
> +1. Style the note-taking-app.
You could also explain what each selector in the page styles and explain the css properties that are not basic. You can break this down into small chunks instead of pasting the whole css here.

2022-11-05 04:48 UTC, Pranavtechie commented on keep-html5-note-taking-app/step2/challenges.yml
> +  - text: "Try styling the app. (Hint: CSS code is provided in instruction number 1)"
Change the challenge text, removing the words CSS Code is provided.

2022-11-19 12:59 UTC, closed without merging