Adding Files of Watch new Movie #80
codedamn/projects pull request #81
Opened 2022-10-06 18:06 UTC by Zaheer-zk

2022-10-06 18:32 UTC, Pranavtechie requested changes
Hey @Zaheer-zk, you have done a great job in breakdown this project, 

However, I can see a lot of css code snippets in the Instructions file, this is not a bad thing, but it would be great if you can also drop some explanation for why the property is used and how this will affect the style of the page. 

These changes would drastically improves the learning experience of the user while building the project.

2022-10-06 18:32 UTC, Pranavtechie commented on watch-new-movie/spec.yml
> +  The `README.md` file will provide further details about the project. The `style-guide.html` file is where you'll find colors, fonts, etc.
There are NO readme.md file and style-guide available right, so you can delete this line

2022-10-06 18:32 UTC, Pranavtechie commented on watch-new-movie/spec.yml
> +  - Download the starter code and go through the README.md file.
You can delete this line as well

2022-10-07 04:40 UTC, Zaheer-zk commented
Added explanation on  css code snippets in the Instructions file.

2022-11-11 11:47 UTC, Pranavtechie commented
these commits are merged from https://github.com/codedamn/projects/pull/229

2022-11-11 11:47 UTC, closed without merging